version: 2.0

references:
  container_config: &container_config
    docker:
      - image: circleci/ruby:2.4.1

  workspace_root: &workspace_root
    /tmp/workspace
  
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  tag_filter: &tag_filter
    filters:
      branches:
        only: avant-deploy

jobs:
  environment-setup:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: |
          cd /home/circleci/project
          TAG=$(git tag -l | grep -E '^2\.[0-9]{6}' | sort -gr | head -n1 | sed -E 's/\.[0-9]{3}$//')
          echo "export TAG=\"${TAG}\"" >> /tmp/workspace/bash_env
          echo "export IMAGE_ROOT=\"netdisco:${TAG}\"" >> /tmp/workspace/bash_env
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - bash_env

  build-netdisco-postgresql:
    <<: *container_config
    steps:
      - setup_remote_docker
      - checkout
      - *attach_workspace
      - run:
          name: Build netdisco-postgresql
          command: |
            source /tmp/workspace/bash_env
            cd /home/circleci/project/netdisco-postgresql
            docker build -t ${IMAGE_ROOT}-postgresql \
              --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
              --build-arg TAG=${TAG} \
              --build-arg COMMITTISH=${TAG} .
            docker save -o /tmp/workspace/netdisco-postgresql.tar ${IMAGE_ROOT}-postgresql
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - netdisco-postgresql.tar

  build-netdisco-base:
    <<: *container_config
    steps:
      - setup_remote_docker
      - checkout
      - *attach_workspace
      - run:
          name: Build netdisco-base
          command: |
            source /tmp/workspace/bash_env
            cd /home/circleci/project/netdisco-base
            docker build -t ${IMAGE_ROOT}-base \
              --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
              --build-arg TAG=${TAG} \
              --build-arg COMMITTISH=${TAG} .
            docker save -o /tmp/workspace/netdisco-base.tar ${IMAGE_ROOT}-base
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - netdisco-base.tar

  build-netdisco-backend:
    <<: *container_config
    steps:
      - setup_remote_docker
      - checkout
      - *attach_workspace
      - run:
          name: Restore netdisco-base
          command: |
            source /tmp/workspace/bash_env
            docker load -i /tmp/workspace/netdisco-base.tar
            docker tag ${IMAGE_ROOT}-base avantops/${IMAGE_ROOT}-base
      - run:
          name: Build netdisco-backend
          command: |
            source /tmp/workspace/bash_env
            cd /home/circleci/project/netdisco-backend
            docker build -t ${IMAGE_ROOT}-backend \
              --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
              --build-arg TAG=${TAG} \
              --build-arg COMMITTISH=${TAG} .
            docker save -o /tmp/workspace/netdisco-backend.tar ${IMAGE_ROOT}-backend
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - netdisco-backend.tar

  build-netdisco-web:
    <<: *container_config
    steps:
      - setup_remote_docker
      - checkout
      - *attach_workspace
      - run:
          name: Restore netdisco-base
          command: |
            source /tmp/workspace/bash_env
            docker load -i /tmp/workspace/netdisco-base.tar
            docker tag ${IMAGE_ROOT}-base avantops/${IMAGE_ROOT}-base
      - run:
          name: Build netdisco-web
          command: |
            source /tmp/workspace/bash_env
            cd /home/circleci/project/netdisco-web
            docker build -t ${IMAGE_ROOT}-web \
              --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
              --build-arg TAG=${TAG} \
              --build-arg COMMITTISH=${TAG} .
            docker save -o /tmp/workspace/netdisco-web.tar ${IMAGE_ROOT}-web
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - netdisco-web.tar

  build-netdisco-do:
    <<: *container_config
    steps:
      - setup_remote_docker
      - checkout
      - *attach_workspace
      - run:
          name: Restore netdisco-backend
          command: |
            source /tmp/workspace/bash_env
            docker load -i /tmp/workspace/netdisco-backend.tar
            docker tag ${IMAGE_ROOT}-backend avantops/${IMAGE_ROOT}-backend
      - run:
          name: Build netdisco-do
          command: |
            source /tmp/workspace/bash_env
            cd /home/circleci/project/netdisco-do
            docker build -t ${IMAGE_ROOT}-do \
              --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
              --build-arg TAG=${TAG} \
              --build-arg COMMITTISH=${TAG} .
            docker save -o /tmp/workspace/netdisco-do.tar ${IMAGE_ROOT}-do
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - netdisco-do.tar

  upload-netdisco:
    <<: *container_config
    steps:
      - setup_remote_docker
      - *attach_workspace
      - run:
          name: Restore all images
          command: |
            source /tmp/workspace/bash_env
            for image in postgresql backend web do; do
              docker load -i /tmp/workspace/netdisco-$image.tar
            done
      - run:
          name: Retag all images
          command: |
            source /tmp/workspace/bash_env
            for image in postgresql backend web do; do
              docker tag ${IMAGE_ROOT}-$image avantops/${IMAGE_ROOT}-$image
              docker tag ${IMAGE_ROOT}-$image avantops/netdisco:latest-$image
            done
      - run:
          name: Upload all images
          command: |
            source /tmp/workspace/bash_env
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            for image in postgresql backend web do; do
              docker push avantops/${IMAGE_ROOT}-$image
              docker push avantops/netdisco:latest-$image
            done
      - run:
          name: Trigger MicroBadger Index
          command: curl -sL -X POST ${MICROBADGER_TRIGGER}

workflows:
  version: 2
  build-netdisco:
    jobs:
      - environment-setup:
          <<: *tag_filter
      - build-netdisco-postgresql:
          <<: *tag_filter
          requires:
            - environment-setup
      - build-netdisco-base:
          <<: *tag_filter
          requires:
            - environment-setup
      - build-netdisco-backend:
          <<: *tag_filter
          requires:
            - build-netdisco-base
      - build-netdisco-web:
          <<: *tag_filter
          requires:
            - build-netdisco-base
      - build-netdisco-do:
          <<: *tag_filter
          requires:
            - build-netdisco-backend
      - upload-netdisco:
          <<: *tag_filter
          requires:
            - build-netdisco-backend
            - build-netdisco-web
            - build-netdisco-do
            - build-netdisco-postgresql
